[package]
name = "z2l-core"
description = "Core emulator runtime"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
array-macro = "2.1.5"
bus.workspace = true
log.workspace = true

